config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  resources :users, only: [:index, :show] do
    resources :groups, only: [:index, :show, :new, :create, :destroy] do
      resources :expenses, only: [:index, :show, :new, :create, :destroy] do
          resources :expense_groups, only: [:new, :create, :destroy]
       end
    end
  end
  get '/splash', to: 'groups#splash', as: 'splash'
  authenticated :user do
    root 'groups#index', as: :authenticated_root
  end
  unauthenticated do
    get '/', to: redirect('/splash')
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    user ||= User.new # guest user (not logged in)

    if user.role == 'admin'
      can :manage, :all

    elsif user.role == 'user'
      can :read, :all, user_id: user.id
      can :create, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :expenses_groups, dependent: :destroy
  has_many :groups, through: :expenses_groups
  validates :name, presence: true
  validates :amount, numericality: { is_decimal: true }
  attr_accessor :group_id
end

app/models/expenses_group.rb
class ExpensesGroup < ApplicationRecord
  belongs_to :group
  belongs_to :expense
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :expenses_groups, dependent: :destroy
  has_many :expenses, through: :expenses_groups
  validates :name, :icon, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :expenses, dependent: :destroy
  has_many :groups, dependent: :destroy

  validates :name, presence: true, length: { minimum: 2, maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:splash]
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to request.referrer, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    attributes = %i[name]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: %i[show edit update destroy]

  # GET /expenses or /expenses.json
  def index
    @expenses = Expense.all
  end

  # GET /expenses/1 or /expenses/1.json
  def show; end

  # GET /expenses/new
  def new
    @expense = Expense.new
    @group = current_user.groups.all
  end

  # GET /expenses/1/edit
  def edit; end

  # POST /expenses or /expenses.json
  def create
    @expense = Expense.new(expense_params)
    @expense.author_id = current_user.id

    # Find the group based on the provided group_id

    @group = Group.find(params[:expense][:group_id])

    respond_to do |format|
      if @expense.save

        # Create a new ExpensesGroup record to associate the expense with the group
        ExpensesGroup.create(group: @group, expense: @expense)

        format.html do
          redirect_to user_group_path(@group.user, @group), notice: 'Transaction was successfully created.'
        end
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1 or /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to expense_url(@expense), notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1 or /expenses/1.json
  def destroy
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to user_groups_path, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_expense
    @expense = Expense.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def expense_params
    #   params.require(:expense).permit(:name, :amount, :group_id)
    #   params.require(:expense).permit(:name, :amount, :group_id, :user_id)
    params.require(:expense).permit(:name, :amount, :group_id).merge(author_id: current_user.id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # before_action :set_group, only: %i[show edit update destroy]
  # load_and_authorize_resource
  before_action :authenticate_user!, except: [:splash]
  load_and_authorize_resource except: [:splash]

  # GET /groups or /groups.json
  def index
    @groups = current_user.groups.all.includes(:expenses)
    @total_expenses = current_user.groups.joins(:expenses).sum('expenses.amount')
  end

  def splash; end

  # GET /groups/1 or /groups/1.json
  def show
    @group = Group.find(params[:id])
    render 'show', locals: { group: @group }
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  def create
    @group = current_user.groups.new(group_params)

    if @group.save
      icon_file = params[:group][:icon]
      if icon_file
        icon_filename = icon_file.original_filename
        icon_filepath = Rails.root.join('app', 'assets', 'images', 'icons', icon_filename)
        File.binwrite(icon_filepath, icon_file.read)
        @group.update(icon: "icons/#{icon_filename}")
      end
      redirect_to user_groups_path(current_user), notice: 'Category was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_path, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:user_id, :name, :icon)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/new
  def new
    @user = User.new
  end

  def edit
    # Code for editing a user
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def show
    return unless params[:id] == 'sign_out'

    sign_out_and_redirect
  end

  private

  def sign_out_and_redirect
    sign_out current_user
    redirect_to splash_path
  end

  # Use callbacks to share common setup or constraints between actions.

  def set_user
    @user = current_user
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/expenses/_form.html.erb
<%= render partial: 'shared/nav', locals: {title:'TRANSACTION', symbol:'←', url: user_groups_path}%>
<div class="category_form">
<%= form_with(model: expense, url: user_group_expenses_path) do |form| %>
  <div class="transaction">
    <h3 class="">Add Transaction</h3>
  

  <div class="form_div">
    <%= form.text_field :name, placeholder: "Transaction Name", class: "login-field" %>
  </div><br>

  <div class="form_div">
    <%= form.text_field :amount, placeholder: "Enter Amount", class: "login-field" %>
  </div><br>

  <div class="form_divas">
    <label class="name_label">Select category</label>
    <%= form.select :group_id, @group.all.collect {|u| [u.name.capitalize, u.id] }, class:'' %>
  </div>

  <div class=''>
    <%= form.submit "Add transaction", class:"category_button" %>
  </div>
  </div>
<% end %>
</div>

app/views/expenses/new.html.erb
<section class="">
  <%= render "form", expense: @expense %>
</section>

app/views/groups/_form.html.erb
<%= render partial: 'shared/nav', locals: {title:'CATEGORY', symbol:'←', url: user_groups_path}%>

<%= form_with model: group, url: user_groups_path, local: true, multipart: true  do |form| %>  
  <div class="category_form">
    <h3 > Add New Category </h3>
      <div class="form_div">
      <% form.label :name  %>
      <%= form.text_field :name, placeholder: "Category Name", class: "login-field"%>
      <% form.object.errors.full_messages_for(:name).each do |message|%>
      <div><%= message %></div>
      <%end%>
    </div>
      <br>
     <div class="form_diva">
    <%= form.label :icon, 'Chose icon:', class: 'labela' %><br>
      <%= form.file_field :icon, class: "chose-icon" %>
        <% form.object.errors.full_messages_for(:icon).each do |message|%>
        <div><%= message %></div>
        <%end%>
     </div>
     <br>
      <%= form.submit "Create Category", class:"category_button"%>
    </div>
<%end%>

app/views/groups/index.html.erb
<%= render partial: 'shared/nav', locals: {title:'CATEGORIES', symbol:'', url:
''}%>

<section class="body_container">
  <p><%= notice %></p>
  <div class="total_box">
    <p class="group_name">
      Total expenses for <%= current_user.name.titleize %>
    </p>
    <p class="total_amount">$<%=@total_expenses %></p>
  </div>
  <div>
    <% @groups.includes(:expenses).each do |group| %> <%= render partial:
    'shared/group', locals: {group:group}%> <%end%>
  </div>
  <div class="button_box">
    <div class="push_box">
      <%= button_to 'ADD CATEGORY', new_user_group_path(user_id:
      current_user.id), method: :get, class: 'add_category fixed-bottom'%>
    </div>
  </div>
</section>

app/views/groups/new.html.erb
<section class="">
  <div class="">
    <%= render "form", group: @group %>
  </div>
</section>

app/views/groups/show.html.erb
<%= render partial: 'shared/nav', locals: {title:'TRANSACTION', symbol:'←', url:
:back}%>

<section class="">
  <p class="text-center mb-2"><%= notice %></p>
  <%= render 'shared/detail', group:@group%> <%
  @group.expenses.order(created_at: :desc).each do |g| %>
  <div class="transact_card">
    
    <ul class="group_card_detail-inner">
      <h4>
        <%= g.name.capitalize %></h3>
      </h4>
      <li>$<%= g.amount %></li>
    </ul>
    <div><%= g.created_at.strftime("%d %b %Y") %></div>
    
  </div>
  <% end %> <%= button_to 'ADD TRANSACTION',
  new_user_group_expense_path(user_id: group.user.id, group_id: group.id),
  method: :get, class: 'category_button fixed-bottom' %>
</section>

app/views/groups/splash.html.erb
<section class="">
  <div class="splash_container">
    <h1 class="splash_name">
      Budget App
    </h1>
        <p class="splash_p">
      A user-friendly app to help you track your expenses.
    </p>
    </div>
    <div class="">
      <%= button_to "SIGN IN", new_user_session_path, method: :get, class: 'login_splash' %>
      <%= button_to "SIGN UP", new_user_registration_path, method: :get, class: 'logout_splash' %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://fonts.cdnfonts.com/css/proxima-nova-2" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
         <%= stylesheet_link_tag 'style', "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_detail.html.erb
<div class="group_card">
<div class="group_card_image">
<%= image_tag(group.icon, alt: 'Image Description', class: 'group_image') %>
</div>  
<h2 class=""><%=  group.name %></h2>
<p class="amount"> $<%= group.expenses.sum(:amount) %> </p> 
</div>

app/views/shared/_group.html.erb
<div class="group_card">
  <div class="group_card_image">
    <%= image_tag(group.icon, alt: 'Image Description', class: 'group_image') %>
  </div>
  
  <div class="group_card_detail">
    <div class="group_card_detail-inner">
      <h2 class="group_name">
        <%= link_to group.name, user_group_path(group.user, group) %>
      </h2>
      <p class="amount">$<%= group.expenses.sum(:amount) %></p>
    </div>
    <p class="date"><%= group.created_at.strftime("%d %b %Y") %></p>
  </div>
</div>

app/views/shared/_nav.html.erb
<section >
  <nav class='navbar'>
  <P>
    <span class='arrow-link'>
      <%= link_to symbol, url, class: 'arrow-link' %>
    </span> </P>
    <h2 class='login'>
      <%= title %>
    </h2>
    <div class="logout">
      <% if user_signed_in? %>
        <%= button_to 'Log out', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Log in', new_user_session_path %>
      <% end %>
    
    </div>
  </nav>
</section>